"""
Level 2 - Streamlit Application Example
========================================
This script runs as a CML Application (start_application task).

It demonstrates:
  - Reading Job output files (CSV + JSON) generated by Level 1 Job
  - Building an interactive Streamlit dashboard
  - Graceful fallback when output files don't exist yet
  - Using environment variables for configuration
"""

import os
import json
from pathlib import Path

import pandas as pd
import streamlit as st

REPORT_DIR = os.environ.get("REPORT_OUTPUT_DIR", "outputs")
REPORT_NAME = os.environ.get("REPORT_NAME", "data_report")

CSV_PATH = Path(REPORT_DIR) / f"{REPORT_NAME}.csv"
JSON_PATH = Path(REPORT_DIR) / f"{REPORT_NAME}.json"

st.set_page_config(
    page_title="Hello World AMP Dashboard",
    page_icon="🌐",
    layout="wide",
)


# ── Header ────────────────────────────────────────────────────────────────────

st.title("Hello World AMP — Data Report Dashboard")
st.caption("Level 2 · Cloudera AI · Applied ML Prototype")
st.divider()


# ── Check if Job has been run ─────────────────────────────────────────────────

if not CSV_PATH.exists() or not JSON_PATH.exists():
    st.warning(
        f"Report files not found in `{REPORT_DIR}/`. "
        "Please run the **Data Report Job** first from the Jobs menu, "
        "then refresh this page.",
        icon="⚠️",
    )
    st.info(
        "**How to run the Job:**\n"
        "1. Go to **Jobs** in the left menu\n"
        "2. Click **Data Report Job**\n"
        "3. Click **Run Job**\n"
        "4. Come back here and refresh",
        icon="ℹ️",
    )
    st.stop()


# ── Load data ─────────────────────────────────────────────────────────────────

@st.cache_data
def load_data():
    df = pd.read_csv(CSV_PATH)
    with open(JSON_PATH) as f:
        summary = json.load(f)
    return df, summary


df, summary = load_data()


# ── KPI Metrics ───────────────────────────────────────────────────────────────

st.subheader("Key Metrics")

col1, col2, col3, col4 = st.columns(4)

col1.metric(
    label="Total Active Users",
    value=f"{summary['active_users']['total']:,}",
)
col2.metric(
    label="Avg Usage Score",
    value=summary["usage_score"]["mean"],
)
col3.metric(
    label="Top Product",
    value=summary["usage_score"]["top_product"],
)
col4.metric(
    label="Products Tracked",
    value=summary["row_count"],
)

st.divider()


# ── Charts ────────────────────────────────────────────────────────────────────

chart_col, table_col = st.columns([3, 2])

with chart_col:
    st.subheader("Usage Score by Product")
    chart_df = df.set_index("product")[["usage_score"]]
    st.bar_chart(chart_df, color="#00BC73", height=300)

with table_col:
    st.subheader("Active Users by Category")
    category_data = pd.DataFrame(summary["by_category"])
    category_data.columns = ["Category", "Total Users"]
    st.dataframe(
        category_data,
        use_container_width=True,
        hide_index=True,
    )

st.divider()


# ── Raw Data Table ────────────────────────────────────────────────────────────

with st.expander("Raw Dataset", expanded=False):
    st.dataframe(df, use_container_width=True, hide_index=True)
    st.download_button(
        label="Download CSV",
        data=CSV_PATH.read_bytes(),
        file_name=CSV_PATH.name,
        mime="text/csv",
    )


# ── Footer ────────────────────────────────────────────────────────────────────

st.divider()
st.caption(
    f"Report generated at: `{summary['generated_at']}` · "
    f"Python `{summary['python_version']}` · "
    f"Source: `{CSV_PATH}`"
)
